#!/bin/bash
#
# description: this file is sourced via the aliases-init script

__parse_script_arguments() {
    while (( "${#}" )); do
        case "${1}" in
            --operating-system|--os)
				[ "${2}" != 'linux' ] && [ "${2}" != 'windows' ] && [ "${2}" != 'wsl' ] && echo "ERROR: unrecognized ${1} parameter ${2}" && return 1
                operating_sys="${2}"
                shift
				;;
            *)
                echo "ERROR: arg ${1} is unexpected" && return 2
                ;;
        esac
        shift
    done
}

_aliases_source(){
	## default values
	local operating_sys=''
    ## fill script vars with cmd line args and/or default values where applicable
    __parse_script_arguments "${@}" || return "1${?}"
	## hardcoded values
	local script_path="${BASH_SOURCE[0]}"
	######### cfg  #########
	local open=''; { [ "${operating_sys}" == 'linux' ] && open='xdg-open'; } || { [ "${operating_sys}" == 'windows' ] && open='start'; } || { [ "${operating_sys}" == 'wsl' ] && open='wsl-open'; } || ! echo "ERROR: unable to set open var" || return 1
	######### func #########
	cd_parent_aliases() { local ALS='.'; local DIR; for VAR in {1..10} ; do ALS="${ALS}."; DIR="${DIR}../"; alias "${ALS}"'=cd '"${DIR}"; done }
	######### git  #########
	alias gg='git status -sb'
	alias gc='git checkout'
	alias gcm='git checkout master'
	alias gf='git fetch'
	alias gp='git pull'
	alias grom='git fetch && git rebase origin/master'
	alias lg='git log --date=format:"%d-%m-%Y %H:%M" --pretty=format:"%h%x20%x20%Cred%ad%x20%x20%Cblue%an%x20%x20%Creset%s"'
	alias log='git log --graph --abbrev-commit --decorate --format=format:"%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset) %C(bold cyan)(committed: %cD)%C(reset) %C(auto)%d%C(reset)%n''          %C(white)%s%C(reset)%n''          %C(dim white)- %an <%ae> %C(reset) %C(dim white)(committer: %cn <%ce>)%C(reset)"'
	alias ggg='git submodule foreach git status -sb'
	alias gsu='git submodule update'
	alias gss='git submodule status'
	######### dirs #########
	cd_parent_aliases
	alias dl="cd ${HOME}/Downloads"
	alias dsk="cd ${HOME}/Desktop"
	alias doc="cd ${HOME}/Documents"
	######### misc #########
	alias op="${open}"
	alias rc="${open} ${HOME}/.bashrc"
	alias rca="${open} ${HOME}/.bash_aliases"
	alias rcg="${open} ${script_path}"
	alias rcs="source ${HOME}/.bashrc"
	alias rcas="source ${HOME}/.bash_aliases"
	alias rcgs="source ${script_path}"
	[ "${operating_sys}" == 'windows' ] || alias sudo='sudo ' # purpose is to allow 'sudo <alias>'
	alias rs='reset'
}

_aliases_source "${@}" || exit "${?}"
